CREATE TABLE PREDIO(
    COD_PRED INT NOT NULL, 
    NOME_PRED VARCHAR(40) NOT NULL
);

CREATE TABLE SALA(
    NUM_SALA INT  NOT NULL, 
    COD_PRED INT NOT NULL,
    DESCRICAO_SALA VARCHAR(40) NOT NULL, 
    CAPAC_SALA INT NOT NULL
);

CREATE TABLE HORARIO(
    ANO_SEM INT  NOT NULL, 
    COD_DEPTO CHAR(5) NOT NULL, 
    NUM_DISC INT NOT NULL, 
    SIGLA_TURMA CHAR(2) NOT NULL,
    DIA_SEM INT NOT NULL, 
    HORA_INICIO INT NOT NULL, 
    NUM_SALA INT NOT NULL, 
    COD_PRED INT NOT NULL, 
    NUM_HORAS INT NOT NULL
);
    
CREATE TABLE TURMA(
    ANO_SEM INT NOT NULL, 
    COD_DEPTO CHAR(5) NOT NULL,
    NUM_DISC INT NOT NULL, 
    SIGLA_TURMA CHAR(2) NOT NULL, 
    CAPAC_TURMA INT NOT NULL
);
    
CREATE TABLE DISCIPLINA(
    COD_DEPTO CHAR(5) NOT NULL, 
    NUM_DISC INT NOT NULL, 
    NOME_DISC VARCHAR(10) NOT NULL, 
    CREDITO_DISC INT NOT NULL
);

CREATE TABLE PRE_REQ(
    COD_DEPTO_PRE_REQ CHAR(5) NOT NULL, 
    NUM_DISC_PRE_REQ INT NOT NULL, 
    COD_DEPTO CHAR(5) NOT NULL, 
    NUM_DISC INT NOT NULL
);
    
CREATE TABLE DEPTO(
    COD_DEPTO CHAR(5) NOT NULL, 
    NOME_DEPTO VARCHAR(40) NOT NULL
);

CREATE TABLE PROFESSOR(
    COD_PROF INT NOT NULL, 
    COD_DEPTO CHAR(5) NOT NULL, 
    COD_TIT INT NOT NULL, 
    NOME_PROF VARCHAR(40) NOT NULL
);

CREATE TABLE PROF_TURMA(
    ANO_SEM INT NOT NULL, 
    COD_DEPTO CHAR(5) NOT NULL, 
    NUM_DISC INT NOT NULL, 
    SIGLA_TURMA CHAR(2) NOT NULL, 
    COD_PROF INT NOT NULL
);
    
CREATE TABLE TITULACAO(
    COD_TIT INT NOT NULL, 
    NOME_TIT VARCHAR(40) NOT NULL
);
