CREATE TABLE SEG_MERCADO(
    ID NUMBER (5),
    DESCRICAO VARCHAR2(100)
);

CREATE TABLE CLIENTE(
    ID NUMBER (5),
    RAZAO_SOCIAL VARCHAR2(100),
    CNPJ VARCHAR2(20),
    SEG_MERCADO_ID NUMBER(5),
    DATA_INCLUSAO DATE,
    FATURAMENTO_PREVISTO NUMBER(10,2),
    CATEGORIA VARCHAR2(20)
);