CREATE TABLE IF NOT EXISTS PROF_TURMA(
    ANO_SEM INT unsigned NOT NULL, 
    COD_DEPTO CHAR(5) NOT NULL, 
    NUM_DISC INT unsigned NOT NULL, 
    SIGLA_TURMA CHAR(2) NOT NULL, 
    COD_PROF INT unsigned NOT NULL
);
