CREATE TABLE IF NOT EXISTS TURMA(
    ANO_SEM INT unsigned NOT NULL, 
    COD_DEPTO CHAR(5) NOT NULL,
    NUM_DISC INT unsigned NOT NULL, 
    SIGLA_TURMA CHAR(2) NOT NULL, 
    CAPAC_TURMA INT unsigned NOT NULL
);
